#!/bin/bash
# shellcheck shell=bash
# Shared fixtures for the projection tests (sourced; bash 3.2).
#
#   fx_project            create a Spec Kit project with the extension
#                         installed (vendored copy of extension/ + a
#                         .registry entry) and a minimal policy; prints its
#                         directory. Nothing is projected yet.
#   fx_registry <dir> <v> rewrite the registry entry's version
#   fx_cleanup <dir>      remove a fixture

FX_REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

fx_project() {
    local d v
    d="$(mktemp -d 2>/dev/null || mktemp -d -t gates-fx)" || return 1
    d="$(cd "$d" && pwd -P)"
    (
        cd "$d" || exit 1
        git init -q . && git config user.email fx@example.invalid && git config user.name fx
        mkdir -p .specify/extensions/gates .specify/gates
        cp -R "$FX_REPO_ROOT/extension/extension.yml" "$FX_REPO_ROOT/extension/runtime" \
            "$FX_REPO_ROOT/extension/ci" "$FX_REPO_ROOT/extension/commands" .specify/extensions/gates/
        # Like Spec Kit's zip extraction: only *.sh keep the execute bit.
        chmod 644 .specify/extensions/gates/runtime/hooks/git/pre-commit \
            .specify/extensions/gates/runtime/hooks/git/pre-merge-commit \
            .specify/extensions/gates/runtime/hooks/git/commit-msg
        printf '{ "hooks": {} }\n' >.specify/gates/policy.json
    ) || return 1
    v="$(sed -n 's/^  version: *"\{0,1\}\([0-9][0-9.]*\)"\{0,1\} *$/\1/p' "$d/.specify/extensions/gates/extension.yml" | head -n 1)"
    fx_registry "$d" "$v"
    printf '%s\n' "$d"
}

fx_registry() { # <dir> <version>
    printf '{"schema_version":"1.0","extensions":{"gates":{"version":"%s","source":"local","enabled":true}}}\n' \
        "$2" >"$1/.specify/extensions/.registry"
}

fx_cleanup() { # <dir>
    # A coverage run keeps sandboxes: bashcov reports a traced script only
    # if the file still exists when the run ends (#98).
    [[ -n "${GATES_KEEP_TMP:-}" ]] && return 0
    [[ -n "${1:-}" && -d "$1" ]] && rm -rf "$1"
    return 0
}

# fx_precommit_hook <hooks-dir> <hook> [wired]
#   write the hook `pre-commit install` generates, as pre-commit 4.x runs it
#   in migration mode (#201): it refuses arguments for pre-commit and
#   pre-merge-commit, runs an executable <hook>.legacy first, keeps going
#   when that fails, then runs its configured items (with "wired": the
#   gates <hook>), and fails when either failed. pre-commit itself need not
#   be installed.
fx_precommit_hook() {
    cat >"$1/$2" <<HOOK
#!/bin/sh
# File generated by pre-commit: https://pre-commit.com
case "$2" in
    pre-commit | pre-merge-commit)
        [ \$# -eq 0 ] || { echo "hook-impl for $2 expected 0 arguments but got \$#" >&2; exit 1; } ;;
esac
rc=0
if [ -x "\$0.legacy" ]; then
    PRE_COMMIT_RUNNING_LEGACY=1 "\$0.legacy" "\$@" || rc=1
fi
if [ "${3:-}" = "wired" ]; then
    bash "\$(git rev-parse --show-toplevel)/.specify/gates/hooks/$2" "\$@" || rc=1
fi
exit \$rc
HOOK
    chmod +x "$1/$2"
}
