#!/bin/bash
# shellcheck shell=bash
set -euo pipefail

# Generate extension/runtime/lib/known-releases.sha256: the hash of every
# file each released version projected (feature 005, research R4).
#
# project.sh reads it when a project has no .projected.sha256 yet (every
# 0.3.x projection): a projected file that matches a released version of
# itself was never edited locally, so an upgrade may replace it. Without
# the table, every file that changed between releases would be reported as
# a local edit on the first upgrade.
#
# Usage: scripts/known-releases.sh [--check]
#   (no flag)  rewrite the table from the release tags
#   --check    exit 1 if the committed table differs from a fresh build
#
# The projection mapping comes from the current lib/manifest.sh, applied to
# each tag's extension/runtime/, so old and new projections are described
# the same way. Covers the releases that projected without a manifest:
# v0.3.0 (the first with a .runtime-version marker) up to, not including,
# 0.4.0. Every later projection writes .projected.sha256, so new releases
# never need to be added here.

REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO/extension/runtime/lib/known-releases.sha256"
# shellcheck source=/dev/null
source "$REPO/extension/runtime/lib/manifest.sh"

TAGS="$(git -C "$REPO" tag -l 'v[0-9]*' | sed 's/^v//' \
    | awk -F. '$1 == 0 && $2 == 3' | sort -t. -k1,1n -k2,2n -k3,3n)"
[[ -n "$TAGS" ]] || { echo "known-releases: no v0.3.x release tags (fetch tags first)" >&2; exit 2; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
build() {
    printf '# Generated by scripts/known-releases.sh -- do not edit.\n'
    printf '# <version>\\t<sha256>\\t<projected path>, for every file each release projected.\n'
    local v d s r
    for v in $TAGS; do
        d="$TMP/$v"
        mkdir -p "$d"
        git -C "$REPO" archive "v$v" extension/runtime | tar -x -C "$d"
        while IFS=$'\t' read -r s r; do
            [[ -n "$s" ]] || continue
            printf '%s\t%s\t%s\n' "$v" "$(gates_sha256 "$d/extension/runtime/$s")" "$r"
        done < <(gates_projection_table "$d/extension/runtime" 1)
    done
}

if [[ "${1:-}" == "--check" ]]; then
    build >"$TMP/fresh"
    if ! cmp -s "$TMP/fresh" "$OUT"; then
        echo "known-releases: $OUT is stale; run scripts/known-releases.sh" >&2
        exit 1
    fi
    exit 0
fi
build >"$OUT.tmp" && mv -f "$OUT.tmp" "$OUT"
echo "known-releases: wrote $(grep -vc '^#' "$OUT") entries for: $(tr '\n' ' ' <<<"$TAGS")"
